global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'carnetroute'

scrape_configs:
  - job_name: 'carnetroute-backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nats'
    static_configs:
      - targets: ['nats:8222']
    metrics_path: /metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []
