apiVersion: v1
kind: Secret
metadata:
  name: carnetroute-secrets
  namespace: carnetroute
type: Opaque
stringData:
  DATABASE_USER: "carnetroute"
  DATABASE_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  JWT_SECRET: "CHANGE_ME_MIN_32_CHARS_IN_PRODUCTION"
  REDIS_PASSWORD: ""
