ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [ com.carnetroute.ApplicationKt.module ]
  }
}

app {
  environment = "dev"
  environment = ${?APP_ENV}

  jwt {
    secret = "change-me-in-production-use-env-var"
    secret = ${?JWT_SECRET}
    issuer = "carnetroute"
    audience = "carnetroute-users"
    expiresInSeconds = 3600
    refreshExpiresInSeconds = 604800
  }

  database {
    url = "jdbc:postgresql://localhost:5432/carnetroute"
    url = ${?DATABASE_URL}
    user = "postgres"
    user = ${?DATABASE_USER}
    password = "password"
    password = ${?DATABASE_PASSWORD}
    maxPoolSize = 10
  }

  redis {
    url = "redis://localhost:6379"
    url = ${?REDIS_URL}
  }

  nats {
    url = "nats://localhost:4222"
    url = ${?NATS_URL}
  }

  cors {
    allowedOrigins = ["http://localhost:4202", "http://localhost", "http://localhost:8090"]
  }
}
